### PR TITLE
Dev/docusaurus cleanup

### PR DESCRIPTION
**Pull request by jmoggr**

### CODE REVIEW

**Comment by ryscheng** [comment]
Cool thanks!

**Review by ryscheng — APPROVED** [review]
Cool thanks!

**Comment by ccerv1** [comment]
@jmoggr I'm seeing some conflicts in the PR

**Comment by ryscheng** [comment]
Looks like holke took care of most of these changes in a separate commit here
https://github.com/Network-Goods/hypercerts/commit/b6029b5b36497b531bfedde8899971dd6f137223

**Pull request closed without merging**
